# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 10) do

  create_table "answers", :force => true do |t|
    t.column "question_id", :integer,  :null => false
    t.column "content",     :text,     :null => false
    t.column "user_id",     :integer,  :null => false
    t.column "created_on",  :datetime, :null => false
    t.column "updated_on",  :datetime, :null => false
  end

  create_table "articles", :force => true do |t|
    t.column "user_id",      :integer,                                     :null => false
    t.column "category",     :string,   :limit => 128
    t.column "title",        :string,   :limit => 64,                      :null => false
    t.column "subtitle",     :string,   :limit => 64
    t.column "abstract",     :string,   :limit => 1024,                    :null => false
    t.column "publishdate",  :datetime
    t.column "content",      :text
    t.column "created_on",   :datetime
    t.column "updated_on",   :datetime
    t.column "lock_version", :integer,                  :default => 0
    t.column "teaser_id",    :integer
    t.column "status",       :string,   :limit => 64,   :default => "new"
    t.column "slug",         :string,   :limit => 64
  end

  create_table "articles_images", :id => false, :force => true do |t|
    t.column "article_id", :integer
    t.column "image_id",   :integer
  end

  create_table "contributors", :force => true do |t|
    t.column "article_id", :integer,  :null => false
    t.column "user_id",    :integer,  :null => false
    t.column "role",       :string,   :null => false
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
  end

  create_table "groups", :force => true do |t|
    t.column "name",        :string,   :limit => 64, :null => false
    t.column "description", :text
    t.column "created_on",  :datetime
    t.column "created_by",  :integer
  end

  create_table "groups_users", :id => false, :force => true do |t|
    t.column "group_id",   :integer, :null => false
    t.column "user_id",    :integer, :null => false
    t.column "created_on", :date
  end

  create_table "headline_discussions", :force => true do |t|
    t.column "show_id",     :integer, :null => false
    t.column "headline_id", :integer, :null => false
    t.column "position",    :integer, :null => false
  end

  create_table "headlines", :force => true do |t|
    t.column "user_id",    :integer,                                    :null => false
    t.column "created_at", :datetime,                                   :null => false
    t.column "updated_at", :datetime,                                   :null => false
    t.column "title",      :string,   :limit => 64,                     :null => false
    t.column "content",    :text
    t.column "status",     :string,   :limit => 64,  :default => "new"
    t.column "url",        :string,   :limit => 256
  end

  create_table "images", :force => true do |t|
    t.column "name",             :string,   :limit => 64
    t.column "mimetype",         :string,   :limit => 64
    t.column "height",           :integer
    t.column "width",            :integer
    t.column "data",             :binary
    t.column "user_id",          :integer
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
    t.column "alternative_text", :string,   :limit => 64
  end

  create_table "images_shows", :id => false, :force => true do |t|
    t.column "image_id", :integer, :null => false
    t.column "show_id",  :integer, :null => false
  end

  create_table "participants", :force => true do |t|
    t.column "show_id",    :integer,  :null => false
    t.column "user_id",    :integer,  :null => false
    t.column "role",       :string,   :null => false
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
  end

  create_table "questions", :force => true do |t|
    t.column "title",        :string,   :limit => 64,                     :null => false
    t.column "content",      :text,                                       :null => false
    t.column "person_name",  :string,   :limit => 64,                     :null => false
    t.column "location",     :string,   :limit => 64,                     :null => false
    t.column "user_id",      :integer,                                    :null => false
    t.column "created_on",   :datetime,                                   :null => false
    t.column "updated_on",   :datetime,                                   :null => false
    t.column "person_email", :string,   :limit => 254
    t.column "status",       :string,   :limit => 64,  :default => "new"
  end

  create_table "questions_shows", :id => false, :force => true do |t|
    t.column "question_id", :integer
    t.column "show_id",     :integer
  end

  create_table "shows", :force => true do |t|
    t.column "title",          :string,   :limit => 64,                     :null => false
    t.column "category",       :string,   :limit => 254
    t.column "promo",          :text
    t.column "abstract",       :text,                                       :null => false
    t.column "content",        :text
    t.column "user_id",        :integer,                                    :null => false
    t.column "created_on",     :datetime,                                   :null => false
    t.column "updated_on",     :datetime,                                   :null => false
    t.column "status",         :string,   :limit => 64,  :default => "new"
    t.column "showtime",       :datetime
    t.column "teaser_id",      :integer
    t.column "planning_notes", :text
    t.column "lock_version",   :integer,                 :default => 0
  end

  create_table "users", :force => true do |t|
    t.column "login",        :string, :limit => 80
    t.column "password",     :string
    t.column "display_name", :string, :limit => 64
    t.column "email",        :string, :limit => 128
  end

end
